version: '3.9'
services:
  db:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hello1997
      POSTGRES_DB: people
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'microservice@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'microservice'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped